# Array creation:conversion from other Python structures

In [9]:
import numpy as np
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size


9

In [14]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [15]:
zeros=np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 5)

In [19]:
range=np.arange(15)

In [20]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace=np.linspace(1,10,3)

In [22]:
lspace

array([ 1. ,  5.5, 10. ])

In [23]:
emp=np.empty((4,6))

In [24]:
emp

array([[ 6.56835492e-312,  6.56809016e-312,  3.27693980e-319,
         2.88646609e-309,  4.06548999e-309, -1.80463451e+090],
       [ 1.13314747e-311, -8.82504362e+218,  1.41377619e-309,
         3.28958788e-319,  2.89189840e-309,  4.08178692e-309],
       [-1.80463451e+090,  1.13314747e-311, -7.62145642e+141,
         1.41377619e-309,  3.28958788e-319,  2.89733071e-309],
       [-7.97929385e+141,  1.40834479e-309,  3.27693980e-319,
        -1.07153983e+243,  3.47880506e-196,  2.68776652e-317]])

In [25]:
emp_like=np.empty_like(lspace)

In [26]:
emp_like

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [27]:
ide=np.identity(45)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
arr=np.arange(99)

In [31]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr=arr.reshape(3,33)

In [33]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr=arr.ravel()

In [35]:
arr.shape

(99,)

In [36]:
arr.shape

(99,)

# operation with 2d numpy

In [37]:
x = [[1,2,3], [4,5,6], [7,1,0] ]

In [38]:
ar = np.array(x)



In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.sum(axis=0)

array([12,  8,  9])

In [41]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [42]:
ar.T


array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
ar.flat

In [44]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [45]:
ar.ndim

2

In [46]:
ar.size

9

In [47]:
ar.nbytes


36

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.argmin()

8

In [50]:
ar.argmax()

6

In [51]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [52]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [53]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [54]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [55]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [59]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [60]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [61]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [62]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [63]:
one.argmax()

NameError: name 'one' is not defined

In [ ]:
np.sqrt(ar)

: 

In [ ]:
one.argmin()

: 

In [ ]:
ar.sum()

: 

In [ ]:
ar.max()

: 

In [ ]:
ar.min()

: 

In [ ]:
one.argsort()

: 

In [ ]:
ar

: 

In [ ]:
np.where(ar>5)

: 

In [ ]:
type(np.where(ar>5))

: 

In [ ]:
np.count_nonzero(ar)

: 

In [ ]:
np.nonzero(arr)

: 

In [ ]:
np.nonzero(ar)

: 

# new sum 2d

In [ ]:
arr

: 

In [ ]:
[324,24]+[34,546]

: 

In [ ]:
ar+ar2

: 

In [ ]:
ar*ar2

: 

In [ ]:
ar-ar2

: 

: 