# Array creation:conversion from other Python structures

In [67]:
import numpy as np
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [68]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [69]:
listarray.dtype

dtype('int32')

In [70]:
listarray.shape

(3, 3)

In [71]:
listarray.size


9

In [72]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [73]:
zeros=np.zeros((2,5))

In [74]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [75]:
zeros.dtype

dtype('float64')

In [76]:
zeros.shape

(2, 5)

In [77]:
range=np.arange(15)

In [78]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [79]:
lspace=np.linspace(1,10,3)

In [80]:
lspace

array([ 1. ,  5.5, 10. ])

In [81]:
emp=np.empty((4,6))

In [82]:
emp

array([[6.56835492e-312, 6.56809016e-312, 3.27693980e-319,
        2.88646609e-309, 4.06548999e-309, 1.80463451e+090],
       [1.13314747e-311, 8.82504362e+218, 1.41377619e-309,
        3.28958788e-319, 2.89189840e-309, 4.08178692e-309],
       [1.80463451e+090, 1.13314747e-311, 7.62145642e+141,
        1.41377619e-309, 3.28958788e-319, 2.89733071e-309],
       [7.97929385e+141, 1.40834479e-309, 3.27693980e-319,
        1.07153983e+243, 3.47880506e-196, 2.68776652e-317]])

In [83]:
emp_like=np.empty_like(lspace)

In [84]:
emp_like

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [85]:
ide=np.identity(45)

In [86]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [87]:
ide.shape

(45, 45)

In [88]:
arr=np.arange(99)

In [89]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [90]:
arr=arr.reshape(3,33)

In [91]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [92]:
arr=arr.ravel()

In [93]:
arr.shape

(99,)

In [94]:
arr.shape

(99,)

# operation with 2d numpy

In [95]:
x = [[1,2,3], [4,5,6], [7,1,0] ]

In [96]:
ar = np.array(x)



In [97]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [98]:
ar.sum(axis=0)

array([12,  8,  9])

In [99]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [100]:
ar.T


array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [101]:
ar.flat

In [102]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [103]:
ar.ndim

2

In [104]:
ar.size

9

In [105]:
ar.nbytes


36

In [106]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [107]:
ar.argmin()

8

In [108]:
ar.argmax()

6

In [109]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [110]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [111]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [112]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [113]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [115]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [116]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [117]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [118]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [119]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [120]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [121]:
one=np.array([1,2,3,4,5])
one.argmax()

4

In [122]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [123]:
one.argmin()

0

In [124]:
ar.sum()

29

In [125]:
ar.max()

7

In [126]:
ar.min()

0

In [127]:
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [128]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [129]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [130]:
type(np.where(ar>5))

tuple

In [131]:
np.count_nonzero(ar)

8

In [132]:
np.nonzero(arr)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
        69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
        86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98], dtype=int64),)

In [133]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

# new sum 2d

In [134]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [135]:
[324,24]+[34,546]

[324, 24, 34, 546]

In [136]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [137]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [138]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])