# Welcome to numpy

In [2]:
import numpy as np

In [3]:
myarr=np.array([[3,6,37,7]],np.int64)

In [4]:
myarr[0 , 1,]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,1]=45

In [8]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

# Array creation:conversion from other Python structures

In [9]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size


9

In [14]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [15]:
zeros=np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 5)

In [19]:
range=np.arange(15)

In [20]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace=np.linspace(1,10,3)

In [22]:
lspace

array([ 1. ,  5.5, 10. ])

In [23]:
emp=np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56600486e-307, 4.45055939e-308, 1.42419530e-306],
       [1.60219035e-306, 1.42419938e-306, 7.56603881e-307,
        8.45603440e-307, 3.56043054e-307, 1.60219306e-306],
       [6.23059726e-307, 1.06811422e-306, 3.56043054e-307,
        1.37961641e-306, 9.45697982e-308, 8.01097889e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.33510679e-306, 2.22522597e-306, 8.01097889e-307]])

In [25]:
emp_like=np.empty_like(lspace)

In [26]:
emp_like

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [27]:
ide=np.identity(45)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
arr=np.arange(99)

In [31]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr=arr.reshape(3,33)

In [33]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr=arr.ravel()

In [35]:
arr.shape

(99,)

In [36]:
arr.shape

(99,)

# operation with 2d numpy

In [37]:
x = [[1,2,3], [4,5,6], [7,1,0] ]

In [38]:
ar = np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.sum(axis=0)

array([12,  8,  9])

In [41]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [42]:
ar.T


array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
ar.flat

In [44]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [45]:
ar.ndim

2

In [46]:
ar.size

9

In [47]:
ar.nbytes


36

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.argmin()

8

In [50]:
ar.argmax()

6

In [51]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [52]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [53]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [54]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [55]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

# operation with 1d numpy

In [56]:
one=np.array([1,3,4,634,2])

In [57]:
one.argmax()

3

In [58]:
one.argmin()

0

In [59]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)