# Linear Algebra

In [1]:
import numpy as np

In [2]:
A=np.array([[6,1,1],[4,-2,5],[2,8,7]])

In [3]:
A


array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [4]:
np.linalg.matrix_rank(A)

3

In [5]:
np.linalg.det(A)

-306.0

In [7]:
np.trace(A)

11

In [8]:
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [9]:
np.linalg.matrix_power(A,3)

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])

In [10]:
B=np.array([[8,-8,-2],[4,-3,-2],[3,-4,1]])

In [11]:
B


array([[ 8, -8, -2],
       [ 4, -3, -2],
       [ 3, -4,  1]])

In [12]:
np.linalg.eigh(B)

(array([-7.11486688,  3.44465311,  9.67021377]),
 array([[-0.31324628, -0.06105536, -0.94770724],
        [ 0.8007754 , -0.55344937, -0.22902523],
        [ 0.51052476,  0.83064194, -0.22225759]]))

In [14]:
B=np.diag((1,2,3))

In [16]:
np.linalg.eig(B)

(array([1., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))